/**
 * @file test_spgemm_hc_lsh.cpp
 * @brief MinHash+LSH -> hierarchical clustering -> Vlength-cluster -> LeSpGEMM_VLength.
 *        Performance test only: candidate pairs from LSH (no file input).
 */

#include "../include/SpOps.h"
#include "../include/spgemm.h"
#include "../include/timer.h"
#include "../include/cmdline.h"
#include "../include/sparse_io.h"
#include "../include/sparse_conversion.h"
#include "../include/spgemm_utility.h"
#include "../include/spgemm_MinHashLSH.h"
#include <iostream>
#include <cstdlib>
#include <cstring>
#include <string>
#include <map>
#include <vector>
#ifdef _OPENMP
#include <omp.h>
#endif

using namespace std;

static void usage(int argc, char **argv) {
    std::cout << "Usage:\n";
    std::cout << "\t" << argv[0] << " <A.mtx> <B.mtx> [options]\n";
    std::cout << "\t  Candidate pairs are generated by MinHash+LSH (no candidate file).\n";
    std::cout << "\tOptions:\n";
    std::cout << "\t  --precision     = 32|64 (default 64)\n";
    std::cout << "\t  --threads      = number of OMP threads\n";
    std::cout << "\t  --iterations   = iterations for performance (default 10)\n";
    std::cout << "\t  --kernel       = 1 (Hash VLength) or 2 (Array VLength, default 1)\n";
    std::cout << "\t  --cluster_size = max cluster size (default 8)\n";
    std::cout << "\t  --sort         = 0|1 (sort output columns, default 0)\n";
    std::cout << "\t  --k            = MinHash signature length (default 64)\n";
    std::cout << "\t  --bands        = LSH bands, k % bands == 0 (default 16)\n";
    std::cout << "\t  --seed         = LSH/MinHash random seed (default 7)\n";
}

template <typename IndexType, typename ValueType>
void test_spgemm_hc_lsh_performance(const char *matA_path, const char *matB_path,
                                    int iterations, int kernel_flag, bool sortOutput,
                                    IndexType cluster_size, int k, int num_bands, uint64_t seed)
{
    cout << "========================================" << endl;
    cout << "MinHash+LSH -> Vlength-Cluster SpGEMM Performance" << endl;
    cout << "========================================" << endl;

    cout << "Reading A: " << matA_path << endl;
    CSR_Matrix<IndexType, ValueType> A_csr = read_csr_matrix<IndexType, ValueType>(matA_path);
    cout << "A: " << A_csr.num_rows << " x " << A_csr.num_cols << ", nnz: " << A_csr.num_nnzs << endl;

    cout << "Reading B: " << matB_path << endl;
    CSR_Matrix<IndexType, ValueType> B = read_csr_matrix<IndexType, ValueType>(matB_path);
    cout << "B: " << B.num_rows << " x " << B.num_cols << ", nnz: " << B.num_nnzs << endl;

    if (A_csr.num_cols != B.num_rows) {
        cerr << "Error: A.cols != B.rows" << endl;
        delete_host_matrix(A_csr);
        delete_host_matrix(B);
        return;
    }

    if (k <= 0 || num_bands <= 0 || k % num_bands != 0) {
        cerr << "Error: k must be positive and k % bands == 0. k=" << k << " bands=" << num_bands << endl;
        delete_host_matrix(A_csr);
        delete_host_matrix(B);
        return;
    }

    cout << "Generating candidate pairs by MinHash+LSH (k=" << k << ", bands=" << num_bands << ", seed=" << seed << ")..." << endl;
    anonymouslib_timer timer;
    timer.start();
    std::map<std::pair<IndexType, IndexType>, ValueType> close_pairs = lsh_candidate_pairs<IndexType, ValueType>(
        A_csr.row_offset, A_csr.col_index, A_csr.num_rows, k, num_bands, seed);
    double t_lsh_ms = timer.stop();
    cout << "LSH candidate pairs: " << close_pairs.size() << " (genPairs time: " << t_lsh_ms << " ms)" << endl;

    cout << "Hierarchical clustering (cluster_size=" << cluster_size << ")..." << endl;
    timer.start();
    std::map<IndexType, std::vector<IndexType>> reordered_dict = hierarchical_clustering_v0<IndexType, ValueType>(
        A_csr.row_offset, A_csr.col_index, A_csr.num_rows, close_pairs, cluster_size);
    std::vector<IndexType> permutation, offsets;
    reordered_dict_to_permutation_and_offsets<IndexType>(reordered_dict, A_csr.num_rows, permutation, offsets);
    double t_hc_ms = timer.stop();
    cout << "Clusters: " << reordered_dict.size() << " (HC time: " << t_hc_ms << " ms)" << endl;

    cout << "Reordering A by cluster..." << endl;
    CSR_Matrix<IndexType, ValueType> A_reordered = csr_reorder_rows<IndexType, ValueType>(A_csr, permutation);
    cout << "Converting A to CSR_VlengthCluster..." << endl;
    timer.start();
    CSR_VlengthCluster<IndexType, ValueType> A_cluster = csr_to_vlength_cluster<IndexType, ValueType>(A_reordered, offsets);
    double t_convert_ms = timer.stop();
    cout << "Format Conversion time: " << t_convert_ms << " ms" << endl;
    delete_host_matrix(A_reordered);
    cout << "A_cluster: " << A_cluster.rows << " clusters, nnzc=" << A_cluster.nnzc << ", nnzv=" << A_cluster.nnzv << endl;

    long long int flops = get_spgemm_flop(A_csr, B);
    cout << "FLOPs: " << flops << endl;
    cout << "Kernel: " << kernel_flag << endl;

    CSR_VlengthCluster<IndexType, ValueType> C_cluster;
    if (sortOutput)
        LeSpGEMM_VLength<true, IndexType, ValueType>(A_cluster, B, C_cluster, kernel_flag);
    else
        LeSpGEMM_VLength<false, IndexType, ValueType>(A_cluster, B, C_cluster, kernel_flag);
    delete_vlength_cluster_matrix(C_cluster);

    double total_ms = 0.0;
    for (int i = 0; i < iterations; i++) {
#ifdef _OPENMP
        double t0 = omp_get_wtime();
#else
        double t0 = static_cast<double>(clock()) / CLOCKS_PER_SEC;
#endif
        if (sortOutput)
            LeSpGEMM_VLength<true, IndexType, ValueType>(A_cluster, B, C_cluster, kernel_flag);
        else
            LeSpGEMM_VLength<false, IndexType, ValueType>(A_cluster, B, C_cluster, kernel_flag);
#ifdef _OPENMP
        double t1 = omp_get_wtime();
#else
        double t1 = static_cast<double>(clock()) / CLOCKS_PER_SEC;
#endif
        total_ms += (t1 - t0) * 1000.0;
        if (i < iterations - 1) delete_vlength_cluster_matrix(C_cluster);
    }
    double avg_ms = total_ms / iterations;
    cout << "Average time (LeSpGEMM_VLength): " << avg_ms << " ms" << endl;
    cout << "Average GFLOPS: " << (flops / 1e9) / (avg_ms / 1000.0) << endl;

    delete_vlength_cluster_matrix(C_cluster);
    delete_vlength_cluster_matrix(A_cluster);
    delete_host_matrix(A_csr);
    delete_host_matrix(B);
    cout << "Performance test done." << endl;
}

template <typename IndexType, typename ValueType>
void run_spgemm_hc_lsh_test(int argc, char **argv)
{
    char *matA = NULL, *matB = NULL;
    int n = 0;
    for (int i = 1; i < argc; i++) {
        if (argv[i][0] != '-') {
            if (n == 0) { matA = argv[i]; n++; }
            else if (n == 1) { matB = argv[i]; n++; break; }
        }
    }
    if (!matA || !matB) {
        printf("Error: need A.mtx B.mtx\n");
        usage(argc, argv);
        return;
    }

    int iterations = 10;
    char *p = get_argval(argc, argv, "iterations");
    if (p) iterations = atoi(p);

    int kernel_flag = 1;
    p = get_argval(argc, argv, "kernel");
    if (p) {
        kernel_flag = atoi(p);
        if (kernel_flag != 1 && kernel_flag != 2) kernel_flag = 1;
    }

    IndexType cluster_size = 8;
    p = get_argval(argc, argv, "cluster_size");
    if (p) cluster_size = static_cast<IndexType>(atoi(p));

    bool sortOutput = false;
    p = get_argval(argc, argv, "sort");
    if (p) sortOutput = (atoi(p) != 0);

    int k = 64;
    p = get_argval(argc, argv, "k");
    if (p) k = atoi(p);

    int num_bands = 16;
    p = get_argval(argc, argv, "bands");
    if (p) num_bands = atoi(p);

    uint64_t seed = 7;
    p = get_argval(argc, argv, "seed");
    if (p) seed = static_cast<uint64_t>(atoll(p));

    cout << "A: " << matA << ", B: " << matB << endl;
    cout << "LSH: k=" << k << ", bands=" << num_bands << ", seed=" << seed << endl;
    cout << "kernel: " << kernel_flag << ", cluster_size: " << cluster_size << ", iterations: " << iterations << endl;
    cout << "threads: " << Le_get_thread_num() << endl;

    test_spgemm_hc_lsh_performance<IndexType, ValueType>(
        matA, matB, iterations, kernel_flag, sortOutput, cluster_size, k, num_bands, seed);
}

int main(int argc, char *argv[])
{
    if (get_arg(argc, argv, "help") != NULL || argc < 3) {
        usage(argc, argv);
        return EXIT_SUCCESS;
    }

    int precision = 64;
    char *p = get_argval(argc, argv, "precision");
    if (p) precision = atoi(p);

#ifdef CPU_SOCKET
    Le_set_thread_num(CPU_SOCKET * CPU_CORES_PER_SOC);
#else
    Le_set_thread_num(Le_get_core_num());
#endif
    p = get_argval(argc, argv, "threads");
    if (p) Le_set_thread_num(atoi(p));

    printf("Precision: %d-bit, threads: %d\n\n", precision, Le_get_thread_num());

    if (precision == 32)
        run_spgemm_hc_lsh_test<int64_t, float>(argc, argv);
    else if (precision == 64)
        run_spgemm_hc_lsh_test<int64_t, double>(argc, argv);
    else {
        usage(argc, argv);
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;
}
